package types

// Actor представляет текущего пользователя (авторизованного)
type Actor struct {
	ID                              string          `json:"id"`
	Username                        string          `json:"username"`
	Status                          string          `json:"status"`
	Email                           string          `json:"email"`
	Type                            string          `json:"type"`
	Verified                        bool            `json:"verified"`
	ProfilePicture                  string          `json:"profilepicture"`
	Description                     string          `json:"description"`
	Slogan                          string          `json:"slogan"`
	Fullname                        string          `json:"fullname"`
	LevelDescription                string          `json:"level_description"`
	Cover                           string          `json:"cover"`
	GoodReviews                     int             `json:"good_reviews"`
	BadReviews                      int             `json:"bad_reviews"`
	Location                        string          `json:"location"`
	Rating                          float64         `json:"rating"`
	RatingCount                     int             `json:"rating_count"`
	TotalAmount                     int             `json:"total_amount"`
	HoldAmount                      int             `json:"hold_amount"`
	FreeAmount                      int             `json:"free_amount"`
	Currency                        string          `json:"currency"`
	InboxArchiveCount               int             `json:"inbox_archive_count"`
	UnreadDialogCount               int             `json:"unread_dialog_count"`
	NotifyUnreadCount               int             `json:"notify_unread_count"`
	RedNotify                       bool            `json:"red_notify"`
	WarningInboxCount               int             `json:"warning_inbox_count"`
	AppNotifyCount                  int             `json:"app_notify_count"`
	UnreadMessagesCount             int             `json:"unread_messages_count"`
	FullnameEn                      string          `json:"fullnameEn,omitempty"`
	DescriptionEn                   string          `json:"descriptionEn,omitempty"`
	CountryID                       int             `json:"country_id"`
	CityID                          int             `json:"city_id"`
	TimezoneID                      int             `json:"timezone_id"`
	AddTime                         int             `json:"addtime"`
	AllowMobilePush                 bool            `json:"allow_mobile_push"`
	IsMorePayer                     bool            `json:"is_more_payer"`
	KworksCount                     int             `json:"kworks_count"`
	FavouriteKworksCount            int             `json:"favourite_kworks_count"`
	HiddenKworksCount               int             `json:"hidden_kworks_count"`
	Specialization                  string          `json:"specialization,omitempty"`
	Profession                      string          `json:"profession,omitempty"`
	KworksAvailableAtWeekends       bool            `json:"kworks_available_at_weekends"`
	AchievementsList                []Achievement   `json:"achievments_list,omitempty"`
	CompletedOrdersCount            int             `json:"completed_orders_count"`
	Kworks                          []KworkObject   `json:"kworks,omitempty"`
	PortfolioList                   []PortfolioItem `json:"portfolio_list,omitempty"`
	Reviews                         []Review        `json:"reviews,omitempty"`
	WorkerStatus                    string          `json:"worker_status"`
	HasOffers                       bool            `json:"has_offers"`
	WantsCount                      int             `json:"wants_count"`
	OffersCount                     int             `json:"offers_count"`
	ArchivedWantsCount              int             `json:"archived_wants_count"`
	PushNotificationsSoundAllowed   bool            `json:"pushNotificationsSoundAllowed"`
	BlackFridayForSellers           bool            `json:"black_friday_for_sellers"`
}
